from python:3.11-slim

env PIP_DISABLE_PIP_VERSION_CHECK=1 
env PYTHONBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN python3 -m venv venv

RUN venv\Scripts\activate

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["uvicorn", "main:app","--reload","--host", "0.0.0.0", "--port", "5000"]